Repository salle-malle/back, pull requests merged in 2025-07, with the labels that each got.

#21 Feat/notification scheduler batch
  build.gradle
  src/main/java/com/shinhan/pda_midterm_project/PdaMidtermProjectApplication.java
  src/main/java/com/shinhan/pda_midterm_project/common/batch/InitialDataLoader.java
  src/main/java/com/shinhan/pda_midterm_project/common/util/SseEmitterRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/config/NotificationBatchConfig.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationService.java
  src/main/java/com/shinhan/pda_midterm_project/test/BatchTestRunner.java
  src/main/resources/application.yml
  src/test/java/com/shinhan/pda_midterm_project/domain/auth/service/NotificationServiceTest.java
Labels: 🛠️BE, ✨feature

#29 Feat: 사용자 보유종목 기준 어닝콜 조회 기능 추가
  data/earnings_calendar_3month.csv
  src/main/java/com/shinhan/pda_midterm_project/common/response/ResponseMessages.java
  src/main/java/com/shinhan/pda_midterm_project/domain/earning_call/model/EarningCall.java
  src/main/java/com/shinhan/pda_midterm_project/domain/earning_call/repository/EarningCallRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/earning_call/service/EarningCallService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/earning_call/service/EarningCallServiceImpl.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/earningCall/controller/EarningCallController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/earningCall/dto/EarningCallResponseDto.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/stock/controller/StockController.java
Labels: ✨feature

#33 Feat/summary investment
  src/main/java/com/shinhan/pda_midterm_project/domain/member/repository/MemberRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/member_stock/repository/MemberStockRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/member_stock_snapshot/repository/MemberStockSnapshotRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/news/repository/NewsRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/news/service/NewsScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/summary/controller/SummaryController.java
  src/main/java/com/shinhan/pda_midterm_project/domain/summary/service/SummaryService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/controller/TotalController.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/model/TotalSummary.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/repository/TotalSummaryRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/service/TotalSummaryService.java
Labels: 🛠️BE, ✨feature

#34 !HOTFIX : 인증 인가 구현 로직을 수정한다
  src/main/java/com/shinhan/pda_midterm_project/common/resolver/AuthenticationResolver.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/model/UserTokens.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/service/AuthService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/service/TokenCookieManager.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/service/TokenProvider.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/auth/controller/AuthController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/auth/dto/response/AuthResponse.java
  src/test/java/com/shinhan/pda_midterm_project/domain/auth/TokenProviderTest.java
  src/test/java/com/shinhan/pda_midterm_project/domain/auth/service/AuthServiceImplTest.java
Labels: 🛠️BE

#51 Feat : 최근 미국 증시 뉴스를 배치로 가져온다
  src/main/java/com/shinhan/pda_midterm_project/common/config/BatchConfig.java
  src/main/java/com/shinhan/pda_midterm_project/common/response/ResponseMessages.java
  src/main/java/com/shinhan/pda_midterm_project/common/scheduler/MainNewsScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/common/util/TimeUtil.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/service/KoreaInvestmentServiceImpl.java
  src/main/java/com/shinhan/pda_midterm_project/domain/main_news/model/MainNews.java
  src/main/java/com/shinhan/pda_midterm_project/domain/main_news/repository/MainNewsRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/main_news/service/MainNewsCrawlingTasklet.java
  src/main/java/com/shinhan/pda_midterm_project/domain/main_news/service/MainNewsService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/main_news/service/MainNewsServiceImpl.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/mainNews/controller/MainNewsController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/news/dto/NewsCrawlingDto.java
Labels: 🛠️BE, ✨feature

#53 Fix : 인증인가 예외처리 수정한다
  src/main/java/com/shinhan/pda_midterm_project/PdaMidtermProjectApplication.java
  src/main/java/com/shinhan/pda_midterm_project/common/resolver/AuthenticationResolver.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/MemberOnlyChecker.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/member/controller/MyPageController.java
Labels: 🛠️BE

#55 Feat/notification read
  src/main/java/com/shinhan/pda_midterm_project/common/response/ResponseMessages.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/model/Notification.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationService.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/notification/controller/NotificationController.java
Labels: 🛠️BE, ✨feature

#60 Feat : CI 파이프라인을 구축한다
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  .github/workflows/deploy-back.yml
  Dockerfile
  src/main/resources/application-coolSMS.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
  src/test/java/com/shinhan/pda_midterm_project/domain/auth/service/NotificationServiceTest.java
Labels: 🛠️BE

#67 Fix : CI 스크립트 파일을 수정한다
  .github/workflows/backend-ci.yml
  src/main/resources/application-prod 2.yml
  src/main/resources/application-prod.yml
Labels: 🐞bug

#68 fix: 뉴스 저장 시 이미지 URL 필드 추가
  src/main/java/com/shinhan/pda_midterm_project/domain/news/service/NewsCrawlingTasklet.java
  src/main/java/com/shinhan/pda_midterm_project/domain/news/service/NewsScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/news/dto/NewsCrawlingDto.java
Labels: 🛠️BE, ✨feature

#69 Fix : 설정 파일을 수정한다
  .github/workflows/deploy-back.yml
  src/main/resources/application.yml
Labels: 🛠️BE

#72 HOTFIX : 설정파일을 변경한다
  src/main/resources/application.yml
Labels: 🐞bug

#85 Feat : 개별 조회 및 1년치 공시데이터 INSERT 로직을 추가한다
  src/main/java/com/shinhan/pda_midterm_project/common/config/BatchConfig.java
  src/main/java/com/shinhan/pda_midterm_project/common/config/DisclosureInitBatch.java
  src/main/java/com/shinhan/pda_midterm_project/common/response/ResponseMessages.java
  src/main/java/com/shinhan/pda_midterm_project/common/util/FastApiClient.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/DisclosureProcessor.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/dto/DisclosureSimpleDto.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/exception/DisclosureException.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/service/DisclosureService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/service/DisclosureServiceImpl.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/disclosure/controller/DisclosureController.java
Labels: 🛠️BE, ✨feature

#87 Feat/notification earning disclosure
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/repository/DisclosureRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/service/DisclosureAlarmScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/earning_call/service/EarningCallAlarmScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/member_stock/repository/MemberStockRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/news/service/NewsScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/model/Notification.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/model/NotificationType.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/service/TotalSummaryService.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/notification/dto/NotificationResponseDto.java
Labels: 🛠️BE, ✨feature

#90 Feat : 내 주신 관련 공시 데이터 전체를 가져오는 api를 구현한다
  src/main/java/com/shinhan/pda_midterm_project/common/handler/GlobalExceptionHandler.java
  src/main/java/com/shinhan/pda_midterm_project/common/response/ResponseMessages.java
  src/main/java/com/shinhan/pda_midterm_project/domain/auth/exception/AuthException.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/repository/DisclosureRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/service/DisclosureService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/service/DisclosureServiceImpl.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/disclosure/controller/DisclosureController.java
Labels: 🛠️BE, ✨feature

#94 Feat/ai markdown format prompts
  src/main/java/com/shinhan/pda_midterm_project/domain/news/repository/NewsRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/news/service/NewsService.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/summary/service/SummaryService.java
Labels: 🛠️BE, ✨feature

#96 Feat : 오늘 내 자산에 대한 총평 summary api를 구현한다
  src/main/java/com/shinhan/pda_midterm_project/common/resolver/AuthenticationResolver.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/repository/TotalSummaryRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/service/TotalSummaryService.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/member/controller/MemberController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/member/dto/response/MemberResponse.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/totalSummary/controller/TotalSummaryController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/totalSummary/dto/TotalSummaryResponseDto.java
Labels: 🛠️BE, ✨feature

#97 Refactor : web client에 있는 fast api uri를 도커 container 이름으로 변경한다
  src/main/java/com/shinhan/pda_midterm_project/common/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: 🛠️BE, ✨feature

#101 Feat/ai markdown format prompts
  .github/pull_request_template.md
  src/main/java/com/shinhan/pda_midterm_project/domain/disclosure/service/DisclosureAlarmScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/news/service/NewsScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/notification/service/NotificationScheduler.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/repository/TotalSummaryRepository.java
  src/main/java/com/shinhan/pda_midterm_project/domain/total_summary/service/TotalSummaryService.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/member/controller/MemberController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/member/dto/response/MemberResponse.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/totalSummary/controller/TotalSummaryController.java
  src/main/java/com/shinhan/pda_midterm_project/presentation/totalSummary/dto/TotalSummaryResponseDto.java
Labels: 🛠️BE, ✨feature

#103 HOTFIX : uri를 컨테이너 아이디로 변경한다
  src/main/java/com/shinhan/pda_midterm_project/common/config/WebClientConfig.java
Labels: 🛠️BE, ✨feature
